# Used by "mix format"
spark_locals_without_parens = [
  action: 1,
  action: 2,
  action: 3,
  action: 4,
  argument: 1,
  argument: 2,
  argument: 3,
  as_options: 1,
  async: 1,
  async_assign: 1,
  close_on_backdrop: 1,
  close_on_escape: 1,
  create: 1,
  data: 1,
  decode: 1,
  default: 1,
  derive: 1,
  derive: 2,
  effect: 1,
  effect: 2,
  emit: 2,
  emit: 3,
  encode: 1,
  flash: 2,
  flash: 3,
  form: 2,
  form: 3,
  from: 1,
  id: 1,
  invalidate: 1,
  invalidate_on: 1,
  invoke: 2,
  invoke: 3,
  max_width: 1,
  module: 1,
  navigate: 1,
  navigate: 2,
  notify_on: 1,
  notify_parent: 1,
  notify_parent: 2,
  on_error: 1,
  on_success: 1,
  open_field: 1,
  params: 1,
  prop: 2,
  prop: 3,
  read: 2,
  read: 3,
  read: 4,
  reads: 1,
  render: 1,
  render: 2,
  render_loading: 1,
  render_loading: 2,
  required: 1,
  run: 1,
  set: 2,
  set: 3,
  setter: 1,
  source: 1,
  state: 2,
  state: 3,
  submit: 1,
  submit: 2,
  transform: 1,
  update: 1,
  update: 2,
  update: 3,
  when: 1
]

[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: spark_locals_without_parens,
  export: [
    locals_without_parens: spark_locals_without_parens
  ]
]
