defmodule Lavash.Lifecycle.AsyncRuntime do
  @moduledoc """
  Runtime support for `async :name do run fn assigns -> ... end end`
  declarations and the `fire :name` op.

  `fire/3` uses `Phoenix.LiveView.start_async/3` to spawn the task,
  which:

    * tracks the task pid on the socket so `render_async/2` in tests
      sees the in-flight work — crucial for parity with vanilla
      `assign_async`/`start_async`
    * routes the result through `handle_async/3` (generated by the
      compile-time transformer; see `handle_lavash_async/3` below)
    * cancels and restarts the task if `fire` is called again while
      one is in flight

  ## Decoupling rationale

  The declaration (what the work IS) lives at the
  `async :name do ... end` site. The trigger (WHEN it runs) lives
  wherever `fire :name` is called — `mount do`, an action body, or
  a message body. One declaration, multiple trigger paths, no
  duplication.
  """

  require Phoenix.LiveView

  alias Lavash.Socket, as: LSocket
  alias Phoenix.LiveView.AsyncResult

  @doc """
  Fire the named async task on the given socket. Looks up the
  module's registered async definitions and starts the task via
  `Phoenix.LiveView.start_async/3`. The field is set to
  `AsyncResult.loading()` immediately.

  Returns the updated socket.
  """
  def fire(socket, module, name) do
    case module.__lavash_async_def__(name) do
      {:ok, run_fn} ->
        assigns = socket.assigns

        socket
        |> LSocket.put_derived(name, AsyncResult.loading())
        |> Phoenix.LiveView.start_async(name, fn -> run_fn.(assigns) end)

      :error ->
        raise ArgumentError,
              "fire :#{name} — no `async :#{name} do ... end` declaration found in #{inspect(module)}"
    end
  end

  @doc """
  Routes a `handle_async/3` callback for a lavash-declared async
  task. Called by the generated `handle_async/3` clause when the
  result name matches a registered `async` declaration.

  Wraps the result in `AsyncResult.ok/1` or `AsyncResult.failed/2`
  to match vanilla `assign_async` shape, then runs through the
  reactive recompute + project pipeline so downstream derived
  fields see the new value.
  """
  def handle_lavash_async(socket, module, name, result) do
    value =
      case result do
        {:ok, {:ok, v}} -> {:ok, v}
        {:ok, v} -> {:ok, v}
        {:exit, reason} -> {:error, reason}
      end

    async_result =
      case value do
        {:ok, v} -> AsyncResult.ok(v)
        {:error, reason} -> AsyncResult.failed(AsyncResult.loading(), {:exit, reason})
      end

    socket
    |> LSocket.put_derived(name, async_result)
    |> Lavash.Reactive.recompute()
    |> Lavash.Assigns.project(module)
  end
end
