defmodule DemoWeb.ProductsLive do
  use Lavash.LiveView
  import Lavash.LiveView.Helpers

  alias Demo.Catalog.{Category, Product}

  # All filter state stored in URL - shareable, bookmarkable, back/forward works
  # setter: true auto-generates set_<name> actions
  state :search, :string, from: :url, default: "", setter: true
  state :category_id, {:uuid, "cat"}, from: :url, default: nil, setter: true
  state :in_stock, :boolean, from: :url, default: nil, setter: true
  state :min_price, :integer, from: :url, default: nil, setter: true
  state :max_price, :integer, from: :url, default: nil, setter: true
  state :min_rating, :integer, from: :url, default: nil, setter: true

  # Modal open state - the modal component handles its own animations internally
  # This field just tracks what product is being edited (nil = closed)
  state :product_id, :any,
    from: :ephemeral,
    default: nil,
    setter: true

  # Products - auto-maps state fields to :list action arguments
  # The action's arguments (search, category_id, in_stock, etc.) match our state field names
  # invalidate: :pubsub enables fine-grained PubSub invalidation using notify_on from the resource
  read :products, Product, :list do
    async false
    invalidate :pubsub
  end

  # Categories - load all categories for the dropdown
  # as_options transforms to [{label, value}, ...] format
  read :category_options, Category do
    async false
    as_options label: :name, value: :id
  end

  # Result count computed from products
  calculate :result_count, rx(length(@products)), optimistic: false

  calculate :has_filters,
            rx(
              @search != "" or @category_id != nil or @in_stock != nil or
                @min_price != nil or @max_price != nil or @min_rating != nil
            ),
            optimistic: false

  actions do
    # set_* actions are auto-generated by setter: true on state fields

    action :clear_filters do
      set :search, ""
      set :category_id, nil
      set :in_stock, nil
      set :min_price, nil
      set :max_price, nil
      set :min_rating, nil
    end
  end

  template """
  <div class="max-w-6xl mx-auto p-6">
    <div class="flex items-center justify-between mb-6">
      <div>
        <h1 class="text-3xl font-bold">Product Catalog (URL State)</h1>
        <p class="text-gray-500 mt-1">Filter state stored in URL - try bookmarking or sharing</p>
      </div>
      <div class="flex gap-4">
        <a href="/demos/products-socket" class="text-indigo-600 hover:text-indigo-800">
          Socket State Version
        </a>
        <a href="/" class="text-indigo-600 hover:text-indigo-800">&larr; Demos</a>
      </div>
    </div>

    <div class="grid grid-cols-4 gap-6">
      <!-- Filters Sidebar -->
      <div class="col-span-1 bg-white rounded-lg shadow p-4 h-fit">
        <div class="flex items-center justify-between mb-4">
          <h2 class="font-semibold text-lg">Filters</h2>
          <button
            :if={@has_filters}
            phx-click="clear_filters"
            class="btn btn-ghost btn-xs text-error"
          >
            Clear all
          </button>
        </div>

        <div class="space-y-4">
          <!-- Search -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Search</label>
            <form phx-change="set_search">
              <input
                type="text"
                name="value"
                value={@search}
                placeholder="Search products..."
                phx-debounce="300"
                class="w-full px-3 py-2 border rounded-md text-sm"
              />
            </form>
          </div>

  <!-- Category -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Category</label>
            <form phx-change="set_category_id">
              <select name="value" class="w-full px-3 py-2 border rounded-md text-sm">
                <option value="">All Categories</option>
                <option
                  :for={{name, id} <- @category_options}
                  value={id}
                  selected={@category_id == id}
                >
                  {name}
                </option>
              </select>
            </form>
          </div>

  <!-- In Stock -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Availability</label>
            <form phx-change="set_in_stock">
              <select name="value" class="w-full px-3 py-2 border rounded-md text-sm">
                <option value="" selected={@in_stock == nil}>All</option>
                <option value="true" selected={@in_stock == true}>In Stock</option>
                <option value="false" selected={@in_stock == false}>Out of Stock</option>
              </select>
            </form>
          </div>

  <!-- Price Range -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Price Range</label>
            <div class="flex gap-2">
              <form phx-change="set_min_price" class="flex-1">
                <input
                  type="number"
                  name="value"
                  value={@min_price}
                  placeholder="Min"
                  class="w-full px-3 py-2 border rounded-md text-sm"
                />
              </form>
              <span class="self-center text-gray-400">-</span>
              <form phx-change="set_max_price" class="flex-1">
                <input
                  type="number"
                  name="value"
                  value={@max_price}
                  placeholder="Max"
                  class="w-full px-3 py-2 border rounded-md text-sm"
                />
              </form>
            </div>
          </div>

  <!-- Min Rating -->
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Minimum Rating</label>
            <form phx-change="set_min_rating">
              <select name="value" class="w-full px-3 py-2 border rounded-md text-sm">
                <option value="" selected={@min_rating == nil}>Any Rating</option>
                <option :for={r <- [4, 3, 2, 1]} value={r} selected={@min_rating == r}>
                  {r}+ stars
                </option>
              </select>
            </form>
          </div>
        </div>

  <!-- Current URL display -->
        <div class="mt-6 pt-4 border-t">
          <p class="text-xs text-gray-400 mb-1">Current filter URL:</p>
          <code class="text-xs bg-gray-100 p-2 rounded block break-all">
            {build_url(assigns)}
          </code>
        </div>
      </div>

  <!-- Products Grid -->
      <div class="col-span-3">
        <div class="flex items-center justify-between mb-4">
          <p class="text-gray-600">
            Showing <span class="font-semibold">{@result_count}</span> products
          </p>
        </div>

        <div class="grid grid-cols-3 gap-4">
          <div
            :for={product <- @products}
            class="bg-white rounded-lg shadow p-4 hover:shadow-md transition-shadow"
          >
            <div class="flex items-start justify-between">
              <h3 class="font-medium text-gray-900">{product.name}</h3>
              <span class={[
                "badge badge-sm",
                product.in_stock && "badge-success",
                !product.in_stock && "badge-error"
              ]}>
                {if product.in_stock, do: "In Stock", else: "Out of Stock"}
              </span>
            </div>
            <p class="text-sm text-gray-500 mt-1">
              {category_name(@category_options, product.category_id)}
            </p>
            <div class="flex items-center justify-between mt-3">
              <span class="text-lg font-bold text-indigo-600">
                ${Decimal.to_string(product.price)}
              </span>
              <span class="text-sm text-yellow-600">
                {"★" |> String.duplicate(round(Decimal.to_float(product.rating)))}
                <span class="text-gray-400 ml-1">{Decimal.to_string(product.rating)}</span>
              </span>
            </div>
            <button
              phx-click={
                Phoenix.LiveView.JS.dispatch("open-panel",
                  to: "#product-edit-modal-modal",
                  detail: %{product_id: product.id}
                )
              }
              class="mt-3 block w-full text-center text-sm text-indigo-600 hover:text-indigo-800 border-t pt-3"
            >
              Edit
            </button>
          </div>
        </div>

        <div :if={@result_count == 0} class="text-center py-12 bg-white rounded-lg shadow">
          <p class="text-gray-500 text-lg">No products match your filters</p>
          <button
            phx-click="clear_filters"
            class="mt-4 text-indigo-600 hover:text-indigo-800"
          >
            Clear all filters
          </button>
        </div>
      </div>
    </div>

    <.lavash_component
      module={DemoWeb.ProductEditModal}
      id="product-edit-modal"
    />
  </div>
  """

  defp build_url(assigns) do
    params =
      %{}
      |> maybe_add("search", assigns.search, "")
      |> maybe_add("category_id", assigns.category_id, nil)
      |> maybe_add("in_stock", assigns.in_stock, nil)
      |> maybe_add("min_price", assigns.min_price, nil)
      |> maybe_add("max_price", assigns.max_price, nil)
      |> maybe_add("min_rating", assigns.min_rating, nil)

    if params == %{} do
      "/products"
    else
      "/products?" <> URI.encode_query(params)
    end
  end

  defp maybe_add(params, _key, value, default) when value == default, do: params
  defp maybe_add(params, key, value, _default), do: Map.put(params, key, value)

  # Works with [{name, id}, ...] format from as_options
  defp category_name(options, category_id) do
    case Enum.find(options, fn {_name, id} -> id == category_id end) do
      nil -> "Uncategorized"
      {name, _id} -> name
    end
  end
end
