defmodule Lavash.Template.ASTTransformer do
  @moduledoc """
  Transforms compiled HEEx template AST to inject Lavash-specific attributes.

  This module post-processes the AST generated by Phoenix's `~H` sigil to:
  - Inject `__lavash_client_bindings__` into `<.child_component>` calls

  Unlike the string-based `Lavash.Template.Transformer`, this operates on the
  compiled AST, making it more robust and compatible with all HEEx features.

  ## How it works

  After `~H` compiles a template, the AST contains component calls as maps with
  keys like `:module`, `:id`, `:__changed__`. We use `Macro.prewalk/2` to find
  these maps and inject additional assigns.

  ## Usage

  This is automatically applied via `@before_compile` in `Lavash.Component.Compiler`.
  You don't need to call this directly.
  """

  @doc """
  Transforms an AST to inject `__lavash_client_bindings__` into component calls.

  Component call maps are identified by having `:module` and `:id` keys.
  If they don't already have `__lavash_client_bindings__`, we inject it with
  the value `assigns.__lavash_client_bindings__`.
  """
  def inject_client_bindings(ast) do
    Macro.prewalk(ast, fn
      # Match map literals: {:%{}, meta, key_value_pairs}
      {:%{}, meta, attrs} = node when is_list(attrs) ->
        if is_component_assigns?(attrs) and not has_client_bindings?(attrs) do
          # Inject __lavash_client_bindings__ accessing assigns
          binding_attr =
            {:__lavash_client_bindings__,
             build_assigns_access(:__lavash_client_bindings__, meta)}

          {:%{}, meta, attrs ++ [binding_attr]}
        else
          node
        end

      node ->
        node
    end)
  end

  # Check if this map looks like component assigns (has :module and :id keys)
  defp is_component_assigns?(attrs) do
    has_key?(attrs, :module) and has_key?(attrs, :id)
  end

  # Check if __lavash_client_bindings__ is already present
  defp has_client_bindings?(attrs) do
    has_key?(attrs, :__lavash_client_bindings__)
  end

  # Check if a key exists in the attribute list
  defp has_key?(attrs, key) do
    Enum.any?(attrs, fn
      {^key, _} -> true
      _ -> false
    end)
  end

  # Build AST for accessing assigns.field
  # Generates: assigns.__lavash_client_bindings__
  defp build_assigns_access(field, meta) do
    line = Keyword.get(meta, :line, 1)

    {{:., [line: line], [{:assigns, [line: line], nil}, field]}, [no_parens: true, line: line],
     []}
  end
end
