defmodule Lavash.LiveView.Compiler do
  @moduledoc """
  Utility functions for LiveView compilation.

  LiveView callbacks are generated by `Lavash.LiveView.Transformers.CompileLiveView`.
  This module provides shared helper functions used by that transformer.
  """

  @doc """
  Generate render/1 function from render function macro.

  Handles `render fn assigns -> ~L\"\"\"...\"\"\" end` (function-based render macro).
  Used as a fallback when pre-tokenized compilation is not available
  (e.g., ~H templates).
  """
  def generate_render_from_template(escaped_fn, _env) do
    quote do
      @impl Phoenix.LiveView
      def render(var!(assigns)) do
        render_fn = unquote(escaped_fn)
        inner_content = render_fn.(var!(assigns))

        Lavash.LiveView.Runtime.wrap_render(__MODULE__, var!(assigns), inner_content)
      end
    end
  end

  @doc """
  Generate synthetic setter actions for state fields with setter: true or optimistic: true.
  """
  def generate_setter_actions(module) do
    module.__lavash__(:states)
    |> Enum.filter(fn
      %Lavash.State.Field{} = f -> f.setter || Lavash.State.Field.optimistic?(f)
      _ -> false
    end)
    |> Enum.map(fn state ->
      %Lavash.Actions.Action{
        name: :"set_#{state.name}",
        params: [:value],
        when: [],
        sets: [
          %Lavash.Actions.Set{
            field: state.name,
            value: & &1.params.value
          }
        ],
        updates: [],
        effects: [],
        submits: [],
        navigates: [],
        flashes: [],
        invokes: []
      }
    end)
  end

  @doc """
  Generate actions from optimistic_action macro definitions.
  """
  def generate_optimistic_actions(module) do
    if function_exported?(module, :__lavash_optimistic_actions__, 0) do
      module.__lavash_optimistic_actions__()
      |> Enum.map(fn {name, field, run_source, _validate_source, _max} ->
        run_fn =
          case Code.string_to_quoted(run_source) do
            {:ok, ast} ->
              {fun, _} = Code.eval_quoted(ast)
              fun

            _ ->
              fn current, _value -> current end
          end

        %Lavash.Actions.Action{
          name: name,
          params: [:value],
          when: [],
          sets: [],
          updates: [
            %Lavash.Actions.Update{
              field: field,
              fun: fn current, context ->
                value = Map.get(context.params, :value)
                run_fn.(current, value)
              end
            }
          ],
          effects: [],
          submits: [],
          navigates: [],
          flashes: [],
          invokes: []
        }
      end)
    else
      []
    end
  end
end
