defmodule Lavash.LiveView.Compiler do
  @moduledoc """
  Utility functions for LiveView compilation.

  LiveView callbacks are generated by `Lavash.LiveView.Transformers.CompileLiveView`.
  This module provides shared helper functions used by that transformer.
  """

  @doc """
  Collect optimistic state fields — both fields declared optimistic and those
  implicitly touched by an optimistic action.
  """
  def collect_optimistic_fields(module) do
    states = module.__lavash__(:states)
    explicitly_optimistic = Enum.filter(states, &Lavash.State.Field.optimistic?/1)
    actions = Spark.Dsl.Extension.get_entities(module, [:actions]) || []

    action_touched_fields =
      actions
      |> Enum.filter(&Lavash.Optimistic.ActionJs.action_is_optimistic?/1)
      |> Enum.flat_map(fn action ->
        sets = action.sets || []
        map_bys = action.map_bys || []
        Enum.map(sets, & &1.field) ++ Enum.map(map_bys, & &1.field)
      end)
      |> MapSet.new()

    explicit_names = MapSet.new(explicitly_optimistic, & &1.name)

    auto_optimistic =
      Enum.filter(states, fn f ->
        f.name in action_touched_fields and f.name not in explicit_names
      end)

    explicitly_optimistic ++ auto_optimistic
  end

  @doc """
  Generate synthetic setter actions for state fields with setter: true or optimistic: true.
  """
  def generate_setter_actions(module) do
    module.__lavash__(:states)
    |> Enum.filter(fn
      %Lavash.State.Field{} = f -> f.setter || Lavash.State.Field.optimistic?(f)
      _ -> false
    end)
    |> Enum.map(fn state ->
      %Lavash.Actions.Action{
        name: :"set_#{state.name}",
        params: [:value],
        when: [],
        sets: [
          %Lavash.Actions.Set{
            field: state.name,
            value: setter_value(state.type)
          }
        ],
        updates: [],
        effects: [],
        submits: [],
        navigates: [],
        flashes: [],
        invokes: []
      }
    end)
  end

  # Generate a type-coercing setter value.
  # Uses rx() expressions so the value is transpilable to JS for optimistic updates.
  defp setter_value(:integer) do
    state_var = Macro.var(:state, nil)

    %Lavash.Rx{
      source: "if(@value == \"\" or @value == nil, do: nil, else: String.to_integer(@value))",
      ast:
        quote do
          value = Map.get(unquote(state_var), :value)

          cond do
            value == "" or value == nil -> nil
            is_integer(value) -> value
            is_binary(value) -> String.to_integer(value)
            true -> value
          end
        end,
      deps: [:value]
    }
  end

  defp setter_value(:boolean) do
    state_var = Macro.var(:state, nil)

    %Lavash.Rx{
      source: "@value == \"true\" or @value == true",
      ast:
        quote(
          do:
            Map.get(unquote(state_var), :value) == "true" or
              Map.get(unquote(state_var), :value) == true
        ),
      deps: [:value]
    }
  end

  defp setter_value(_type) do
    # Default: pass through raw value (strings, atoms, etc.)
    # coerce_value in Action.Runtime handles remaining coercion
    & &1.params.value
  end

  @doc """
  Generate actions from optimistic_action macro definitions.
  """
  def generate_optimistic_actions(module) do
    if function_exported?(module, :__lavash_optimistic_actions__, 0) do
      module.__lavash_optimistic_actions__()
      |> Enum.map(fn {name, field, run_source, _validate_source, _max} ->
        run_fn =
          case Code.string_to_quoted(run_source) do
            {:ok, ast} ->
              {fun, _} = Code.eval_quoted(ast)
              fun

            _ ->
              fn current, _value -> current end
          end

        %Lavash.Actions.Action{
          name: name,
          params: [:value],
          when: [],
          sets: [],
          updates: [
            %Lavash.Actions.Update{
              field: field,
              fun: fn current, context ->
                value = Map.get(context.params, :value)
                run_fn.(current, value)
              end
            }
          ],
          effects: [],
          submits: [],
          navigates: [],
          flashes: [],
          invokes: []
        }
      end)
    else
      []
    end
  end
end
