defmodule DemoWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :demo

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  # max_age makes the anonymous identity persistent: without it the
  # session cookie dies with the browser and every restart mints a new
  # visitor — orphaning their todos, cart, and orders. A year keeps
  # the same user (and their data) across visits; Reset is the
  # deliberate way to start over.
  @session_options [
    store: :cookie,
    key: "_demo_key",
    signing_salt: "cY27hOt0",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 365
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :demo,
    gzip: not code_reloading?,
    only: DemoWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug DemoWeb.Router
end
