defmodule Demo.Repo.Migrations.AddCoffeeFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:products) do
      add :description, :text
      add :weight_oz, :bigint
      add :origin, :text
      add :roast_level, :text
      add :tasting_notes, :text
    end
  end

  def down do
    alter table(:products) do
      remove :tasting_notes
      remove :roast_level
      remove :origin
      remove :weight_oz
      remove :description
    end
  end
end