defmodule Demo.Repo.Migrations.CreateSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:products, primary_key: false) do
      add :category_id,
          references(:categories, column: :id, name: "products_category_id_fkey", type: :uuid)

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :rating, :decimal
      add :in_stock, :boolean
      add :price, :decimal, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:categories, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :slug, :text, null: false
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:categories, [:slug], name: "categories_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:categories, [:slug], name: "categories_unique_slug_index")

    drop table(:categories)

    drop constraint(:products, "products_category_id_fkey")

    drop table(:products)
  end
end