defmodule Demo.Repo.Migrations.ScopeTodosToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:todos) do
      add :user_id, references(:users, column: :id, name: "todos_user_id_fkey", type: :uuid),
        null: false
    end
  end

  def down do
    alter table(:todos) do
      remove :user_id
    end

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `todos` table without the `todos_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."
  end
end