defmodule Demo.Repo.Migrations.CreateOrders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:orders, primary_key: false) do
      add :billing_address_id,
          references(:addresses, column: :id, name: "orders_billing_address_id_fkey", type: :uuid)

      add :shipping_address_id,
          references(:addresses,
            column: :id,
            name: "orders_shipping_address_id_fkey",
            type: :uuid
          )

      add :user_id, references(:users, column: :id, name: "orders_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :card_last_four, :text
      add :payment_method, :text
      add :total, :decimal, null: false
      add :shipping, :decimal, null: false
      add :tax, :decimal, null: false
      add :subtotal, :decimal, null: false
      add :status, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:order_items, primary_key: false) do
      add :product_id,
          references(:products, column: :id, name: "order_items_product_id_fkey", type: :uuid)

      add :order_id,
          references(:orders, column: :id, name: "order_items_order_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :product_name, :text, null: false
      add :unit_price, :decimal, null: false
      add :quantity, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:addresses, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "addresses_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :phone, :text
      add :country, :text, null: false
      add :zip, :text, null: false
      add :state, :text, null: false
      add :city, :text, null: false
      add :apartment, :text
      add :address, :text, null: false
      add :company, :text
      add :last_name, :text, null: false
      add :first_name, :text, null: false
      add :label, :text
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `addresses` table without the `addresses_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:addresses)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `order_items` table without the `order_items_order_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `order_items` table without the `order_items_product_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:order_items)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_shipping_address_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `orders` table without the `orders_billing_address_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:orders)
  end
end