defmodule Demo.Repo.Migrations.CreateTodos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:todos, primary_key: false) do
      add :inserted_at, :utc_datetime_usec, null: false
      add :done, :boolean, null: false
      add :title, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:todos)
  end
end