defmodule Demo.Repo.Migrations.AddAnonymousUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # SQLite doesn't support ALTER COLUMN, so we use a table rebuild approach
    # Create a new table with the correct schema (nullable email/password, new anonymous field)
    execute """
    CREATE TABLE users_new (
      id TEXT PRIMARY KEY,
      email TEXT,
      hashed_password TEXT,
      anonymous INTEGER NOT NULL DEFAULT 0,
      inserted_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )
    """

    # Copy data from old table (existing users are not anonymous)
    execute """
    INSERT INTO users_new (id, email, hashed_password, anonymous, inserted_at, updated_at)
    SELECT id, email, hashed_password, 0, inserted_at, updated_at FROM users
    """

    # Drop old table and rename new one
    execute "DROP TABLE users"
    execute "ALTER TABLE users_new RENAME TO users"

    # Recreate indexes
    execute "CREATE UNIQUE INDEX users_unique_email_index ON users(email) WHERE email IS NOT NULL"
  end

  def down do
    # Create table with original schema
    execute """
    CREATE TABLE users_new (
      id TEXT PRIMARY KEY,
      email TEXT NOT NULL,
      hashed_password TEXT NOT NULL,
      inserted_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )
    """

    # Copy data (this will fail if there are anonymous users without email/password)
    execute """
    INSERT INTO users_new (id, email, hashed_password, inserted_at, updated_at)
    SELECT id, email, hashed_password, inserted_at, updated_at FROM users
    WHERE anonymous = 0
    """

    execute "DROP TABLE users"
    execute "ALTER TABLE users_new RENAME TO users"
    execute "CREATE UNIQUE INDEX users_unique_email_index ON users(email)"
  end
end