defmodule Demo.Repo.Migrations.CreateCarts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:carts, primary_key: false) do
      add :user_id, references(:users, column: :id, name: "carts_user_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:cart_items, primary_key: false) do
      add :product_id,
          references(:products, column: :id, name: "cart_items_product_id_fkey", type: :uuid),
          null: false

      add :cart_id, references(:carts, column: :id, name: "cart_items_cart_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :unit_price, :decimal, null: false
      add :quantity, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:cart_items, [:cart_id, :product_id],
             name: "cart_items_unique_cart_product_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cart_items, [:cart_id, :product_id],
                     name: "cart_items_unique_cart_product_index"
                   )

    drop constraint(:cart_items, "cart_items_cart_id_fkey")

    drop constraint(:cart_items, "cart_items_product_id_fkey")

    drop table(:cart_items)

    drop constraint(:carts, "carts_user_id_fkey")

    drop table(:carts)
  end
end