defmodule Lavash.Transformers.ValidateTemplate do
  @moduledoc """
  Compile-time validation of template-level references against the DSL.

  Where `Lavash.Transformers.ValidateDsl` checks entity-internal
  references (rx body deps, action `reads:` lists, set targets, calc
  deps), this transformer checks **template** references — things the
  user writes in HEEx that resolve to DSL-declared names at runtime.

  ## What's validated

  - `phx-click="action_name"` (and `phx-submit`, `phx-change`,
    `phx-blur`, `phx-focus`, `phx-keydown`, `phx-keyup`,
    `phx-window-keydown`, `phx-window-keyup`) on plain HTML tags must
    refer to a declared `action :name` on the module (or an
    auto-generated setter from `state :name, setter: true` /
    `optimistic: true`).

  ## What's not validated

  - **Dynamic event values** like `phx-click={@some_var}` or
    `phx-click={JS.dispatch(...)}` — the AST is an expression, not a
    static string. We can't know at compile time whether the runtime
    value resolves to a server event name or a JS command.

  - **Events on component nodes** like
    `<.my_component phx-click="...">`. The attribute binds to a
    prop, not an event handler on the host module. Component-level
    events are validated when the component itself compiles.

  - **Events inside untemplated `render fn assigns -> ~H\"...\" end`**
    blocks (without a `template do` block). The token pipeline only
    runs for `template do` content, so non-templated overrides are
    invisible to this check.

  ## Ordering

  Runs after `AnalyzeTemplate` (which collects template event
  references into `:lavash_template_phx_events`) and before the
  Compile{Component,LiveView} transformers.
  """

  use Spark.Dsl.Transformer
  alias Spark.Dsl.Transformer

  def after?(Lavash.Component.Transformers.AnalyzeTemplate), do: true
  def after?(Lavash.Transformers.ValidateDsl), do: true
  def after?(_), do: false

  def before?(Lavash.Component.Transformers.CompileComponent), do: true
  def before?(Lavash.LiveView.Transformers.CompileLiveView), do: true
  def before?(_), do: false

  def transform(dsl_state) do
    module = Transformer.get_persisted(dsl_state, :module)
    events = Transformer.get_persisted(dsl_state, :lavash_template_phx_events) || []

    if events == [] do
      {:ok, dsl_state}
    else
      action_names = collect_action_names(dsl_state)

      case Enum.find(events, fn {name, _meta} -> name not in action_names end) do
        nil ->
          {:ok, dsl_state}

        {name, meta} ->
          {:error, build_error(name, meta, action_names, module)}
      end
    end
  end

  # Action names that can be the target of phx-click etc. Includes:
  #   - Declared `action :foo do ... end`
  #   - Auto-generated `set_foo` setters from
  #     `state :foo, setter: true` or `state :foo, optimistic: true`
  #     (the optimistic flag implies a setter is generated by the
  #     LiveView compiler — see Lavash.LiveView.Compiler.
  #     generate_setter_actions/1)
  #
  # Returned as a MapSet of strings — phx-* attribute values are
  # always strings when statically known.
  defp collect_action_names(dsl_state) do
    actions = Transformer.get_entities(dsl_state, [:actions]) || []
    states = Transformer.get_entities(dsl_state, [:states]) || []

    declared = Enum.map(actions, &to_string(&1.name))

    auto_setters =
      states
      |> Enum.filter(&setter_field?/1)
      |> Enum.map(&"set_#{&1.name}")

    MapSet.new(declared ++ auto_setters)
  end

  defp setter_field?(%{setter: true}), do: true
  defp setter_field?(%{optimistic: true}), do: true

  defp setter_field?(%{animated: animated}) when animated not in [nil, false],
    do: true

  defp setter_field?(_), do: false

  defp build_error(name, meta, action_names, module) do
    suggestion = closest_action(name, action_names)

    suggestion_hint =
      if suggestion do
        "\n\nDid you mean `#{suggestion}`?"
      else
        ""
      end

    line_hint =
      case meta do
        %{line: line} -> " (line #{line})"
        _ -> ""
      end

    %Spark.Error.DslError{
      module: module,
      path: [:template],
      message: """
      phx-event references undeclared action `#{name}`#{line_hint}.

      The template references an event handler that isn't declared in
      this module. Either:

        - Add `action :#{name} do ... end` to the `actions do` block
        - Add `state :#{name}, ..., setter: true` to auto-generate a
          setter action
        - Fix the typo in the template#{suggestion_hint}

      If the value is intentionally not a lavash action (e.g. it's
      handled by a separate Phoenix.LiveView module, or by a
      JS.dispatch command), make the attribute value an expression
      instead of a static string so the validator skips it:

          phx-click={"#{name}"}
      """
    }
  end

  # Best-effort typo suggestion: prefer the action name with the
  # smallest Levenshtein distance. Returns nil if no close match.
  defp closest_action(name, action_names) do
    name_str = to_string(name)

    {best, score} =
      Enum.reduce(action_names, {nil, :infinity}, fn candidate, {best, best_score} ->
        d = levenshtein(name_str, candidate)
        if d < best_score, do: {candidate, d}, else: {best, best_score}
      end)

    # Only suggest if the edit distance is reasonable for a typo —
    # otherwise we'd suggest "save" when the user typed "do_thing_x".
    if best && score <= 3, do: best, else: nil
  end

  defp levenshtein(a, b) when is_binary(a) and is_binary(b) do
    lev(String.graphemes(a), String.graphemes(b))
  end

  defp lev([], b), do: length(b)
  defp lev(a, []), do: length(a)
  defp lev([h | t1], [h | t2]), do: lev(t1, t2)

  defp lev([_ | t1] = a, [_ | t2] = b) do
    1 + Enum.min([lev(t1, b), lev(a, t2), lev(t1, t2)])
  end
end
